name: Master CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.17
      uses: actions/setup-go@v1
      with:
        go-version: 1.17
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build and Run test
      run: |
        echo Running all the tests
        go test
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.17.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true

    - name: Publish the package to go.dev package
      run: |
        git pull
        export latest="$(git describe --tags `git rev-list --tags --max-count=1`)"
        curl https://proxy.golang.org/github.com/Digital-Insight-Technologies-Ltd/gin-jwt-cognito/@v/$latest.info


