name: Release
on:
  push:
    branches:
      - main
      - prod
      - candidate

permissions:
  contents: read # for checkout

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.RELEASE_APP_ID }}
          private-key: ${{ secrets.RELEASE_APP_SECRET }}
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - name: Setup Go
        uses: actions/setup-go@v5

      - name: Build
        run: mkdir -p build && go build -ldflags="-w -s" -o build -v ./...
        env:
          GOOS: linux
          GOARCH: amd64
          CGO_ENABLED: 0

      - name: Test
        run: go test -v ./...

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        id: semantic
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          JIRA_AUTH: ${{ secrets.JIRA_AUTH }}
        with:
          extra_plugins: |
            @jamesbuddrige/semantic-release-jira
            @saithodev/semantic-release-backmerge
            @semantic-release/git

      - name: Upload Artifact to GitHub Release
        uses: softprops/action-gh-release@v2
        if: steps.semantic.outputs.new_release_published == 'true'
        with:
          files: build/*
          tag_name: ${{ steps.semantic.outputs.new_release_git_tag }}